<?php
/****************************THIS SETS UP THE H5B FRAMWORK, CAREFUL***************************************************/

//define('H5B_SHORT',  true); //if you uncomment this, none of the html5 markup will load, but you can still hook in early
define('H5B_COLORS', true); // if you uncomment this, the "candy" colors generated by h5b will be enabled
define('H5B_RESPONSIVE', true); // comment this out to remove the responsive stylesheets provided by h5b
define('H5B_CHILD', true); 
require_once(TEMPLATEPATH.'/lib/h5b-initialize.php'); // if you remove this the fat lady will certianly sing. 

/****************************START EDITING HERE**********************************************************************/
