<?php
/****************************THIS SETS UP THE Q21 FRAMWORK, CAREFUL***************************************************/

//define('Q21_SHORT',  true); //if you uncomment this, none of the html5 markup will load, but you can still hook in early
//define('Q21_COLORS', true); // if you uncomment this, the "candy" colors generated by Q21 will be enabled
define('Q21_RESPONSIVE', true); // comment this out to remove the responsive stylesheets provided by Q21
define('Q21_CHILD', true); 
require_once(TEMPLATEPATH.'/lib/q21-initialize.php'); // if you remove this the fat lady will certianly sing. 

/****************************START EDITING HERE**********************************************************************/
